/*
 * Author: Auto generated by ASP.NET
 * Date Last Modified: 11/27/2021
 * This file contains the class declaration for the Protocols model
 */
using System;

namespace EMT_WebPortal.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}
